name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  copy_with_extension: ^6.0.1
  dart_jsonwebtoken: ^3.2.0
  json_annotation: ^4.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  uuid: ^4.5.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  copy_with_extension_gen: ^6.0.1
  json_serializable: ^6.9.5
  lints: ^5.0.0
  test: ^1.24.0
